networks:
  k6:
  monitoring:

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring

  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - monitoring
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  k6:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./load-test:/scripts

  prometheus:
    image: prom/prometheus
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
