# MySQL
spring.datasource.url=${DB_URL}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate

# JWT
security.whitelist=/api/v1/auth/sign-up,/api/v1/auth/login,/api/v1/auth/email/**,/api/v1/auth/nickname/**,/api/v1/auth/username/**
jwt.secret=${JWT_SECRET}
jwt.access-exp=${JWT_ACCESS_EXP}
jwt.refresh-exp=${JWT_REFRESH_EXP}

# mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}

# AWS S3
aws.region=${AWS_REGION}
aws.s3.bucket=${AWS_S3_BUCKET}
aws.credentials.access-key=${AWS_ACCESS_KEY}
aws.credentials.secret-key=${AWS_SECRET_KEY}
aws.s3.default-profile-image-url=${AWS_S3_DEFAULT_PROFILE_IMAGE_URL}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD:}


# 로그 파일 위치 (ttyd가 보고 있는 app.log 경로로 맞추기)
logging.file.name=/home/ubuntu/springboot/app.log

# 기본 로그 레벨 (root)
logging.level.root=INFO

# 우리 애플리케이션 패키지 로그 레벨 (KomoranUtil 포함)
logging.level.com.wagglex2.waggle=INFO

# 필요하다면 Hibernate SQL 로그는 유지/조절
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE