# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update

# JWT
security.whitelist=/api/v1/auth/sign-up,/api/v1/auth/login,/api/v1/auth/email/**,/api/v1/auth/nickname/**,/api/v1/auth/username/**
jwt.secret=${JWT_SECRET}
jwt.access-exp=${JWT_ACCESS_EXP}
jwt.refresh-exp=${JWT_REFRESH_EXP}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD:}

# mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}

# AWS S3
aws.region=${AWS_REGION}
aws.s3.bucket=${AWS_S3_BUCKET}
aws.credentials.access-key=${AWS_ACCESS_KEY}
aws.credentials.secret-key=${AWS_SECRET_KEY}