# import .env file
spring.config.import=optional:file:.env[.properties]

spring.application.name=waggle

spring.profiles.active=dev

# JPA common option
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

# loggin
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

# Pagination settings
pagination.default-size=20
pagination.max-size=100
pagination.max-page-number=10000

# Swagger UI ??
springdoc.version=V.0.0.1
springdoc.swagger-ui.config-url=/api/v1/api-docs/swagger-config
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# OpenAPI ?? ??
springdoc.api-docs.path=/api/v1/api-docs

#  ??? ?? ???
springdoc.default-consumes-media-type=application/json;charset=UTF-8
springdoc.default-produces-media-type=application/json;charset=UTF-8